#**NumPy**

###NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 


In [ ]:
# importing numpy library 
import numpy as np

###**ndarry (N-dimensional array)**
To define a new ndarray, the easiest way is to use the array() function.


In [ ]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [ ]:
# checking type 
type(x)

numpy.ndarray

In [ ]:
# to know the associated dtype 
x.dtype

dtype('int64')

In [ ]:
# ndim attribute for getting the axes
x.ndim

1

In [ ]:
# size attribute to know array length
x.size

5

In [ ]:
# shape attribute to get its shape
x.shape

(5,)

##**2 Dimensional array**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
# itemsize it defines the size in bytes of each item in the array
a.itemsize

8

In [ ]:
a.data

In [ ]:
# array() function in adddition to the list can accept even tuples and sequences of tuple 
b = np.array([(12, 32, 43), (3, 2, 1)])
b

array([[12, 32, 43],
       [ 3,  2,  1]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# string data type
str_array = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
str_array

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [ ]:
# dtype as argument
c = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [ ]:
# zero() create full array of zeros with dimensions defined by the shape argument

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# ones() create an array full of ones in array
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# arange() for numerical sequence
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(33, 120)

array([ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119])

In [ ]:
# sequence of value with intervals
np.arange(0, 33, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np.arange(0, 10, 0.4)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. , 8.4, 8.8, 9.2, 9.6])

In [ ]:
# reshape() divides a linear array in different part
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# linespace() defines the number of elements into which we want the interval to be split.
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# random() for random value
np.random.random((3, 6))

array([[0.41052366, 0.31048081, 0.4604292 , 0.67927103, 0.93644981,
        0.22229611],
       [0.64638653, 0.22666031, 0.30943739, 0.82653152, 0.90588375,
        0.70269428],
       [0.00695386, 0.12425625, 0.40351387, 0.50995005, 0.99582163,
        0.07155331]])

In [ ]:
np.random.randint(1, 30)

28

#**Basic Operations**

###**Arithmetic operators**

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a+3

array([3, 4, 5, 6, 7])

In [ ]:
a*2

array([0, 2, 4, 6, 8])

In [ ]:
b = np.arange(1, 6)
b

array([1, 2, 3, 4, 5])

In [ ]:
a+b

array([1, 3, 5, 7, 9])

In [ ]:
a-b

array([-1, -1, -1, -1, -1])

In [ ]:
a*b

array([ 0,  2,  6, 12, 20])

In [ ]:
a * np.sin(b)

array([ 0.        ,  0.90929743,  0.28224002, -2.27040749, -3.8356971 ])

In [ ]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
# multidimesional case
a = np.arange(0, 9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a * b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

##**Matrix**

In [ ]:
np.dot(a, b)
# o/p The result at each position is the sum of the products between each element of the corresponding row of the first matrix with the corresponding element of the corresponding column of the second matrix. 

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [ ]:
# alternative way to write dot()
a.dot(b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [ ]:
# a*b != b*a
np.dot(b, a)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

###**Increment and Decrement**

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a +=1
a

array([1, 2, 3, 4])

In [ ]:
a -= 1
a

array([0, 1, 2, 3])

In [ ]:
a +=3
a

array([3, 4, 5, 6])

In [ ]:
a*=3
a

array([ 9, 12, 15, 18])

###**Aggregate Function**

In [ ]:
a = np.array([3.3, 4.3, 1.2, 6.8, 0.5])
a

array([3.3, 4.3, 1.2, 6.8, 0.5])

In [ ]:
a.sum()

16.099999999999998

In [ ]:
a.min()

0.5

In [ ]:
a.max()

6.8

In [ ]:
a.std()

2.2569005294872877

In [ ]:
a.mean()

3.2199999999999998

##**Indexing, Slicing and Iterating**

In [ ]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[4]

14

In [ ]:
a[-1]

15

In [ ]:
a[-4]

12

In [ ]:
a = np.arange(10, 19).reshape((3, 3))
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a[1, 2]

15

**Slicing**

In [ ]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[1:5]

array([11, 12, 13, 14])

In [ ]:
a[1:5:2]

array([11, 13])

In [ ]:
a[::2]

array([10, 12, 14])

In [ ]:
a[:4:2]

array([10, 12])

In [ ]:
a[:5:]

array([10, 11, 12, 13, 14])

In [ ]:
a = np.arange(10, 19).reshape((3, 3))
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a[0:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a[0,:]

array([10, 11, 12])

In [ ]:
a[:,0]

array([10, 13, 16])

In [ ]:
a[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [ ]:
a[[0,2], 0:2]

array([[10, 11],
       [16, 17]])

###**Iterating an Array**

In [ ]:
for i in a:
  print(i)

[10 11 12]
[13 14 15]
[16 17 18]


In [ ]:
# iteration element by element using flat
for item in a.flat:
  print(item)

10
11
12
13
14
15
16
17
18


##**Conditions and Boolean Arrays**

In [ ]:
a = np.random.random((4,4))
a

array([[0.3584518 , 0.78002901, 0.84446792, 0.76066421],
       [0.1916852 , 0.85543599, 0.24213646, 0.71172594],
       [0.39943588, 0.82704192, 0.18120566, 0.57071681],
       [0.83770457, 0.3129971 , 0.28043536, 0.01971571]])

In [ ]:
a < 0.5

array([[ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [False,  True,  True,  True]])

In [ ]:
a[a<0.5]

array([0.3584518 , 0.1916852 , 0.24213646, 0.39943588, 0.18120566,
       0.3129971 , 0.28043536, 0.01971571])

In [ ]:
a > 0.2

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
a <= 0.3

array([[False, False, False, False],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

###**Shape Manipulation**

In [ ]:
a = np.random.random(12)
a

array([0.48958609, 0.84952953, 0.83282219, 0.29846469, 0.03086729,
       0.88705475, 0.71350545, 0.01533726, 0.68412578, 0.71170051,
       0.74933257, 0.86051103])

In [ ]:
# reshape() is used for convert a one-dimensional array into a matrix. 
a = a.reshape(3, 4)
a

array([[0.48958609, 0.84952953, 0.83282219, 0.29846469],
       [0.03086729, 0.88705475, 0.71350545, 0.01533726],
       [0.68412578, 0.71170051, 0.74933257, 0.86051103]])

In [ ]:
a.shape = (3, 4)
a

array([[0.48958609, 0.84952953, 0.83282219, 0.29846469],
       [0.03086729, 0.88705475, 0.71350545, 0.01533726],
       [0.68412578, 0.71170051, 0.74933257, 0.86051103]])

In [ ]:
# ravel() convert a two-dimensional array into a one-dimensional array
a = a.ravel()
a

array([0.48958609, 0.84952953, 0.83282219, 0.29846469, 0.03086729,
       0.88705475, 0.71350545, 0.01533726, 0.68412578, 0.71170051,
       0.74933257, 0.86051103])

In [ ]:
a.shape = (12)
a

array([0.48958609, 0.84952953, 0.83282219, 0.29846469, 0.03086729,
       0.88705475, 0.71350545, 0.01533726, 0.68412578, 0.71170051,
       0.74933257, 0.86051103])

In [ ]:
# transpose() function inverse column with rows.
a.transpose()

array([0.48958609, 0.84952953, 0.83282219, 0.29846469, 0.03086729,
       0.88705475, 0.71350545, 0.01533726, 0.68412578, 0.71170051,
       0.74933257, 0.86051103])

###**Joining array**

In [ ]:
# vstack() it combines the second array as new rows of the first array.
a =np.ones((3,3))
b = np.zeros((3,3))


In [ ]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# hstack() perform horizontal stacking i.e. the second array is added to the columns of the first array.
np.hstack((a, b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
# column_stack() and row_stack() function perform stacking between multiple array.
a = np.array([1,2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.row_stack((a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###**Splitting Arrays**

In [ ]:
# hsplit() divide an array into several part horizontally.
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
[b, c] = np.hsplit(a, 2)
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
# vsplit() divide an array into several part vertically.
[b, c] = np.vsplit(a, 2)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# split() split the array into nonsymmeterical parts.
# (axis = 1) for column and (axis = 0) for row.
[a1, a2, a3] = np.split(a,[1,3], axis=1)
a1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [ ]:
a2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
a3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
[a1, a2, a3] = np.split(a, [1,3], axis=0)
a1

array([[0, 1, 2, 3]])

In [ ]:
a2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[12, 13, 14, 15]])

In [ ]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j),
(3, 'Third', 0.8, 1+3j)])
structured

array([['1', 'First', '0.5', '(1+2j)'],
       ['2', 'Second', '1.3', '(2-2j)'],
       ['3', 'Third', '0.8', '(1+3j)']], dtype='<U21')

##**Reading and Writing Array Data on files**

In [ ]:
# Regarding for saving and then later retrieving data stored in binary format, NumPy provides a pair of functions called save() and load().
a = np.array([[1,2,3], [4,5,6]])
np.save('saved_data', a)

In [ ]:
# load() to load the saved data.
load_data = np.load('saved_data.npy')
load_data

array([[1, 2, 3],
       [4, 5, 6]])

**Reading file with Tabular data**

In [ ]:
# To be able to read your data in a text file and insert them into an array, NumPy provides a function called genfromtxt().
data = np.genfromtxt('data.csv', delimiter=',', names=True)